PR from ayush94582 forked branch
HaikuArchives/Tipster pull request #15
Opened 2016-12-06 03:45 UTC by ayush94582

Resolved bug #7 "Fix Previous Tip" that allows the user to navigate the tips back and forth several times as desired. 
Resolved bug #13 "No Tips in Window" by changing "tips" folder name to "Tipster"

2016-12-06 06:31 UTC, humdingerb requested changes
Pleas also read https://www.haiku-os.org/development/coding-guidelines and correct the few whitespace issues.

2016-12-06 06:31 UTC, humdingerb commented on source/Tipster.cpp
> +	//Ayush updated this method
Remove comment.

2016-12-06 06:31 UTC, humdingerb commented on source/Tipster.cpp
> +//Ayush updated this method to incorporate multiple previous (more stable)
Remove comment.

2016-12-06 06:31 UTC, humdingerb commented on source/Tipster.cpp
> +	 //change folder name of tips to Tipster then change path below
Remove comment.

2016-12-06 06:31 UTC, humdingerb commented on source/Tipster.cpp
> +#include <iostream>
Add new line above and below.

2016-12-06 06:31 UTC, humdingerb commented on source/Tipster.cpp
>   * All rights reserved. Distributed under the terms of the MIT license.
You may add your copyright in the same format under Vale's.

2016-12-06 15:57 UTC, humdingerb requested changes
re-read the style guide...

2016-12-06 15:57 UTC, humdingerb commented on source/Tipster.cpp
>  #include <iostream>
Sorry, I missed that before: <iostream> fits better farther down before <stdio.h>

2016-12-06 15:57 UTC, humdingerb commented on source/Tipster.cpp
> +	ind=0;
Coding style: add spaces before and after "=".
Rename "ind" to something more descriptive.

2016-12-06 15:57 UTC, humdingerb commented on source/Tipster.cpp
> +	if(ind==storepast.CountStrings()-1){
Coding style: space after "if", around "==", around "-", before "{".

2016-12-06 15:57 UTC, humdingerb commented on source/Tipster.cpp
> +		ind=storepast.CountStrings();
Coding style: space around "=".

2016-12-06 15:57 UTC, humdingerb commented on source/Tipster.cpp
> +
remove blank line

2016-12-06 15:57 UTC, humdingerb commented on source/Tipster.cpp
> +	else{
space after "else"

2016-12-06 15:57 UTC, humdingerb commented on source/Tipster.cpp
> +
remove blank line

2017-01-27 18:51 UTC, scottmc commented
Any updates on this?

2017-04-07 06:03 UTC, scottmc submitted a review, later dismissed

2017-04-07 06:08 UTC, scottmc commented
any idea on how to proceed of this?

2017-04-07 06:35 UTC, pulkomandy commented
The conflicts should be solved and I still see some style problems (wrong indentation style in at least one place, I didn't do a very careful review). These should be addressed, preferably by the original submitter, but if he disappeared and isn't interested, we will have to do it ourselves...

2017-04-08 13:00 UTC, AkshayAgarwal007 commented
Apart from the conflicts these are some that are there:
1. the list 'storepast' would store the entire history of tips that are displayed till a certain point. I think having the history longer than the total no. of tips that are there is of no point.
2. Everytime 'fTipsList' becomes empty (after all the tips are displayed) loading of the tips again from the file will take place.

2017-04-09 05:43 UTC, pulkomandy commented
There is now another pull request (#17) that solves this in, I think, a much cleaner way.

2017-04-09 23:55 UTC, scottmc commented
Closing this one then...

2017-04-09 23:55 UTC, closed without merging