Added Polish tips file
HaikuArchives/Tipster pull request #28
Opened 2018-12-11 21:49 UTC by Sudoxo

Translation for the GCI task.

2018-12-11 22:36 UTC, KapiX commented
File encoding is wrong. You have Windows-1252, it should be UTF-8.

2018-12-11 22:40 UTC, KapiX commented on tips/tips-pl.txt
> +Witaj w Tipster! Kliknij w ikon� po lewej stronie wskaz�wki, �eby uzyska� informacje. Kliknij w tekst, �eby przej�� do nast�pnej wskaz�wki.
Kliknij ~w~ tekst

2018-12-11 22:41 UTC, KapiX commented on tips/tips-pl.txt
> +Otw�rz plik, �cie�k�, lub URL w Terminalu, klikaj�c na niego i przytrzymuj�c klawisz ALT.
In Polish we don't use Oxford comma.

2018-12-11 22:48 UTC, KapiX commented on tips/tips-pl.txt
> +Uk�adaj i ��cz okna, przytrzymuj�c klawisz OPT i przesuwaj�c ich kraw�dzie lub tytu�y okienek jedn� obok drugiej.
jedne obok drugich
Source: https://sjp.pwn.pl/poradnia/haslo/Forma-orzeczenia-przy-podmiocie-szeregowym;17749.html

2018-12-11 22:50 UTC, KapiX commented on tips/tips-pl.txt
> +U�yj Workspaces - wirtualnych pulpit�w - �eby podzieli� twoj� prac� a� do 32 przestrzeni roboczych.
https://dev.haiku-os.org/wiki/i18n/pl_PL/StyleGuide#Stosujzasadypolskiejtypografii

swoją pracę aż na 32 przestrzenie robocze

2018-12-11 22:53 UTC, KapiX commented on tips/tips-pl.txt
> +Klikaj�c prawym przyciskiem na zak�adk� okna (lub gdziekolwiek przytrzymuj�c klawisze ALT + CTRL), okno przeniesie si� do ty�u, a klikaj�c dwa razy lewym przyciskiem myszy, mo�emy zminimalizowa� okno
okno zostanie przeniesione na spód, a klikając dwukrotnie lewym przyciskiem myszy, możesz zminimalizować okno do Deskbara.

https://dev.haiku-os.org/wiki/i18n/pl_PL/StyleGuide#Zwracajsi%C4%99doczytelnika

2018-12-11 22:56 UTC, KapiX commented on tips/tips-pl.txt
> +Usprawnij swoj� prac� tworz�c w�asne skr�ty klawiszowe w Preferencjach skr�t�w klawiszowych. (Shortcut Preferences)
w panelu preferencji Shortcuts.

2018-12-11 23:01 UTC, KapiX commented on tips/tips-pl.txt
> +Ustaw plik dzwi�kowy dla "Vision Nick Notification" w ustawieniach d�wi�ku aby otrzymywa� powiadomienie za ka�dym razem kiedy kto� napisze twoje imi� w kliencie IRC.
https://dev.haiku-os.org/wiki/i18n/pl_PL/StyleGuide#Stosujzasadypolskiejtypografii

, aby
, kiedy
powiadomienie dźwiękowe

2018-12-11 23:02 UTC, KapiX commented on tips/tips-pl.txt
> +Przycisk TAB doka�cza komendy i �cie�ki w Terminalu oraz nicki w aplikacji Vision. Po prostu zacznij pisa� i u�yj klawisza TAB aby dopasowa�.
dokańcza -> uzupełnia

, aby znaleźć dopasowanie.

2018-12-11 23:02 UTC, KapiX commented on tips/tips-pl.txt
> +R�ne
Różne

2018-12-11 23:03 UTC, KapiX commented on tips/tips-pl.txt
> +�r�d�o systemu Haiku jest dobrym miejscem przyk�ad�w u�ycia API Haiku. Przeszukaj go dla swojej ulubionej klasy.
Kod źródłowy systemu
przykładów wykorzystania
Przeszukaj go pod kątem swojej

2018-12-11 23:05 UTC, KapiX commented on tips/tips-pl.txt
> +Szybko naci�nij CTRL + TAB, �eby prze��czy� si� pomi�dzy dwiema aplikacjami. Przytrzymaj d�u�ej t� kombinacj� klawiszy, �eby zobaczy� wszystkie dzia�aj�ce aplikacje w Twitcher.
Przytrzymaj *tę* kombinację klawiszy dłużej, aby

2018-12-11 23:06 UTC, KapiX commented on tips/tips-pl.txt
> +Dzi�ki filtrowaniu z wyprzedzeniem Tracker wy�wietla tylko te pliki, kt�rymi jeste� zainteresowany.
które cię interesują

Avoid gendered phrases.

2018-12-11 23:07 UTC, KapiX commented on tips/tips-pl.txt
> +Je�li uwa�asz, �e wolisz korzysta� z gorszego uk�adu klawiszy skr�t�w Linux/Windows (ALT <-> CTRL) mo�esz zmeni� to i par� innych rzeczy w Preferencjach uk�adu klawiszy. (Keymap preferences)
zmienić (typo)
panelu preferencji Keymap.

2018-12-11 23:10 UTC, KapiX commented on tips/tips-pl.txt
> +Upuszczaj�c plik do Terminala, mo�na wstawi� do niego jego �cie�k�. Robi�c to przy u�yciu prawego przycisku myszy mamy do dyspozycji jeszcze inne u�yteczne czynno�ci.
Upuszczenie pliku w Terminalu wstawia jego pełną ścieżkę, to samo przy użyciu prawego przycisku myszy daje do dyspozycje jeszcze inne użyteczne czynności.

2018-12-11 23:13 UTC, KapiX commented on tips/tips-pl.txt
> +W terminalu, komenda "open" otwiera dowolny plik z jego domy�ln� aplikacj�. Dopisuj�c "."/".." otwiera folder bie��cy/nadrz�dny w aplikacji Tracker.
https://dev.haiku-os.org/wiki/i18n/pl_PL/StyleGuide#Stosujzasadypolskiejtypografii

dowolny plik korzystając z przypisanej do niego aplikacji. Z „.” oraz „..” otwiera bieżący/nadrzędny katalog [1] w aplikacji Tracker.

[1] https://dev.haiku-os.org/wiki/i18n/pl_PL/Terminology

2018-12-11 23:15 UTC, KapiX commented on tips/tips-pl.txt
> +Je�li tw�j ulubiony program jest niedost�pny w HaikuDepot, mo�liwe �e b�dziesz musia� doda� kolejne repozytorium. Zobacz zak�adk� "Software" w aplikacji WebPositive.
możliwe że konieczne będzie dodanie kolejnego repozytorium.

Quotes.

2018-12-11 23:16 UTC, KapiX commented on tips/tips-pl.txt
> +Je�li jaki� program ma du�e u�ycie procesora, spr�buj obni�y� jego priorytet u�ywaj�c narz�dzia ProcessController w pasku zada�.
wykorzystuje zbyt wiele czasu procesora

w Deskbarze.

2018-12-11 23:23 UTC, KapiX commented on tips/tips-pl.txt
> +Przytrzymuj�c klawisz SHIFT podczas uruchamiania systemu, mo�na przej�� do opcji boot loader. W�r�d innych ustawie� znajduje si� opcja uruchomienia systemu do konkretnego historycznego stanu Haiku.
możesz dostać się do opcji modułu rozruchu.

Znajduje się tam, między innymi, opcja uruchomienia systemu z konkretnym, poprzednim stanem.

https://www.haiku-os.org/docs/userguide/pl/bootloader.html

2018-12-11 23:25 UTC, KapiX commented on tips/tips-pl.txt
> +Otw�rz panel "Find..." z paska zada� (albo wci�nij ALT + F), �eby znale�� dowolny plik lub folder w systemie. Opr�cz wyszukiwania po nazwie mo�na u�y� innych metod za pomoc� atrybut�w Haiku.
„Znajdź...” z Deskbara

plik lub katalog

można konstruować bardziej skomplikowane zapytania korzystając z atrybutów systemu plików Haiku.

2018-12-11 23:26 UTC, KapiX commented on tips/tips-pl.txt
> +Aby dopasowa� uk�ad klawiatury do twojej fizycznej klawiatury, mo�esz po prostu wybra� jednen z dost�pnych w zak�adce Keymap preferences. Mo�esz r�wnie� zamienia� niekt�re klawisze miejscami przeci�g
jeden z dostępnych układów w panelu preferencji Keymap.

2018-12-11 23:27 UTC, KapiX commented on tips/tips-pl.txt
> +Mo�esz �atwo przesuwa� okienka pomi�dzy obszarami roboczymi, przeci�gaj�c je w aplecie Workspaces. Prze��czanie pomi�dzy obszarami roboczymi jest jeszcze szybsze przy u�yciu kombinacji klawiszy CTRL
okna

CTRL + ALT + strzałki

2018-12-11 23:28 UTC, KapiX commented on tips/tips-pl.txt
> +Naci�nij CTRL + R i zacznij wpisywa� polecenie, a otrzymasz pierwsze dopasowanie z historii wprowadzanych komend. Naciskaj CTRL + R, a� znajdziesz w�a�ciw� lini� komend i naci�nij ENTER aby j� wykona
właściwą komendę

2018-12-11 23:29 UTC, KapiX commented on tips/tips-pl.txt
> +U�yj klawiszy PageUp/PageDown, �eby przewija� strony w rozwijanym menu bardzo zat�oczonego folderu.
katalogu

2018-12-11 23:30 UTC, KapiX commented on tips/tips-pl.txt
> +Mo�esz otworzy� dokument z uruchomion� ju� aplikacj�, przeci�gaj�c jego ikon� na pasek zada�.
w uruchomionej już aplikacji

na wpis aplikacji w Deskbarze

2018-12-11 23:33 UTC, KapiX commented on tips/tips-pl.txt
> +Przytrzymaj lewy ALT + SHIFT + CTRL i kliknij program na pasku zada� aby zako�czy� jego proces. Ta operacja nazywana jest "Vulcan Death Grip".
na pasku zadań -> w Deskbarze
aby go zabić.

„”

2018-12-11 23:34 UTC, KapiX commented on tips/tips-pl.txt
> +Mo�esz prze��cza� si� pomiedzy dwoma obszarami roboczymi, u�ywaj�c skr�tu ALT + ~ (klawisz zale�y od u�ywanego uk�adu klawiatury - to jest klawisz pod ESC na klawiaturze).
Typography (- -> –)

jest to klawisz pod

2018-12-11 23:35 UTC, KapiX commented on tips/tips-pl.txt
> +Przytrzymaj SHIFT podczas przewijania scrollem, �eby przewija� strony w oknach Tracker i w rozwijanych menu.
rolką myszy

2018-12-11 23:36 UTC, KapiX requested changes
Go through existing translations when doing new ones.

https://dev.haiku-os.org/wiki/i18n/pl_PL/StyleGuide
https://dev.haiku-os.org/wiki/i18n/pl_PL/Terminology
https://www.haiku-os.org/docs/userguide/pl/contents.html

2018-12-12 12:46 UTC, Sudoxo commented
Thank you for helping me improve my translation. I introduced the proposed changes.

2019-03-02 01:37 UTC, KapiX approved these changes
There are still some minor issues, but it's OK to be merged.

2019-03-02 07:58 UTC, humdingerb commented
> There are still some minor issues, but it's OK to be merged.

@KapiX, good enough to publish a new version of Tipster, or are there things that need to be fixed first?

2019-03-02 14:29 UTC, KapiX commented
Good enough.

2019-03-03 08:26 UTC, merged

2019-03-03 08:26 UTC, humdingerb commented
OK. Thanks!